// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Student_Center_3._0_Database.Models;

#nullable disable

namespace Student_Center_3._0_API.Migrations
{
    [DbContext(typeof(StudentCenterContext))]
    [Migration("20240919155833_First Migration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Student_Center_3._0_API.Models.Student", b =>
                {
                    b.Property<int>("studentNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("studentNum"));

                    b.Property<string>("birthday")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("middleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("phoneNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("postalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("province")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("socialInsuranceNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("streetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("studentNum");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
